<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-12T22:23:21 IST" name="Default suite" finished-at="2024-11-12T22:24:32 IST" duration-ms="71017">
    <groups>
    </groups>
    <test started-at="2024-11-12T22:23:21 IST" name="Default test" finished-at="2024-11-12T22:24:32 IST" duration-ms="71017">
      <class name="TC_Repo.CON_001">
        <test-method is-config="true" signature="DBConnection()[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:23:21 IST" name="DBConnection" finished-at="2024-11-12T22:23:21 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DBConnection -->
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:23:22 IST" name="launchBrowser" finished-at="2024-11-12T22:23:43 IST" duration-ms="21265" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:23:43 IST" name="loginOperation" finished-at="2024-11-12T22:24:00 IST" duration-ms="16820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method signature="con_001()[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:24:00 IST" name="con_001" finished-at="2024-11-12T22:24:27 IST" duration-ms="26719" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TC_Repo.CON_001.con_001(CON_001.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- con_001 -->
        <test-method is-config="true" signature="logOutOperation()[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:24:27 IST" name="logOutOperation" finished-at="2024-11-12T22:24:32 IST" duration-ms="5157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutOperation -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:24:32 IST" name="CloseBrowser" finished-at="2024-11-12T22:24:32 IST" duration-ms="219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
        <test-method is-config="true" signature="SignOutOperation()[pri:0, instance:TC_Repo.CON_001@55634720]" started-at="2024-11-12T22:24:33 IST" name="SignOutOperation" finished-at="2024-11-12T22:24:33 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignOutOperation -->
      </class> <!-- TC_Repo.CON_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
